CREATE TABLE public.social_network_accounts (
    "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "social_network" text NOT NULL,
    "credentials" jsonb NOT NULL,
    "access_token" jsonb NULL,
    CONSTRAINT social_network_accounts_pk PRIMARY KEY ("id")
);

CREATE TABLE public.social_network_pages (
    "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "account_id" int4 NOT NULL,
    "project" text NOT NULL,
    "page_id" text NOT NULL,
    "page_info" jsonb NOT NULL,
    "access_token" jsonb NUll,
    CONSTRAINT social_network_page_pk PRIMARY KEY ("id"),
    CONSTRAINT pages_fk FOREIGN KEY ("account_id") REFERENCES public.social_network_accounts("id"),
    CONSTRAINT "SOCIAL_NETWORK_PAGES_UNIQUE" UNIQUE ("account_id", "page_id")
)

CREATE TABLE public.posts (
    "id" int8 NOT NULL GENERATED BY DEFAULT AS identity,
    "page" int4 NOT NULL,
    "post_data" jsonb NOT NULL,
    "published_at" timestamptz NOT NULL,
    CONSTRAINT posts_pk PRIMARY KEY ("id"),
    CONSTRAINT posts_fk FOREIGN KEY ("page") REFERENCES public.social_network_pages("id")
)

