CREATE TABLE public.social_accounts (
    "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "network" text NOT NULL,
    "credentials" jsonb NOT NULL,
    CONSTRAINT social_accounts_pk PRIMARY KEY ("id"),
    CONSTRAINT social_accounts_un UNIQUE (network)
);

CREATE TABLE public.groups (
    "account_id" int4 NOT NULL,
    "project" text NOT NULL,
    "group_info" jsonb NOT NULL,
    CONSTRAINT groups_fk FOREIGN KEY ("account_id") REFERENCES public.social_accounts("id")
)