// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package dao

import (
	"autoposting/internal/domain/model"
	"github.com/jackc/pgx/v5/pgtype"
)

type AutopostingPost struct {
	ID          int64
	Page        int
	PostData    model.PostData
	PublishedAt pgtype.Timestamptz
}

type AutopostingSocialNetworkAccount struct {
	ID            int
	SocialNetwork string
	Credentials   string
	AccessToken   model.AccessToken
}

type AutopostingSocialNetworkPage struct {
	ID          int
	AccountID   int
	Project     string
	PageID      string
	PageInfo    model.AccessToken
	AccessToken model.SocialNetworkPageInfo
}
