// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package dao

import (
	"context"
)

type Querier interface {
	CreateSocialNetworkAccount(ctx context.Context, arg CreateSocialNetworkAccountParams) (*AutopostingSocialNetworkAccount, error)
	GetSocialNetworkAccounts(ctx context.Context, arg GetSocialNetworkAccountsParams) ([]*AutopostingSocialNetworkAccount, error)
	UpdateSocialNetworkAccount(ctx context.Context, arg UpdateSocialNetworkAccountParams) error
}

var _ Querier = (*Queries)(nil)
